# Generated by Django 4.1.3 on 2022-11-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
