# Generated by Django 4.1.3 on 2023-01-09 21:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                                        primary_key=True,
                                                        serialize=False,
                                                        to=settings.AUTH_USER_MODEL)),
                ('area', models.CharField(help_text='area',
                                          max_length=32,
                                          validators=[django.core.validators.MinLengthValidator(1)])),
            ],
        ),
    ]
