# Generated by Django 4.1.3 on 2023-01-05 20:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='area',
            field=models.CharField(help_text='area',
                                   max_length=32,
                                   validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(default=5,
                                   help_text='First Name',
                                   max_length=32,
                                   validators=[django.core.validators.MinLengthValidator(1)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(default=5,
                                   help_text='Last Name',
                                   max_length=32,
                                   validators=[django.core.validators.MinLengthValidator(1)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='password',
            field=models.CharField(help_text='Password',
                                   max_length=256,
                                   validators=[django.core.validators.MinLengthValidator(6)]),
        ),
        migrations.AlterField(
            model_name='client',
            name='user_name',
            field=models.CharField(help_text='User Name',
                                   max_length=32,
                                   primary_key=True,
                                   serialize=False,
                                   validators=[django.core.validators.MinLengthValidator(6)]),
        ),
    ]
