# Generated by Django 4.1.3 on 2023-01-05 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0003_alter_client_area_alter_client_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_account',
            field=models.OneToOneField(null=True,
                                       on_delete=django.db.models.deletion.CASCADE,
                                       to=settings.AUTH_USER_MODEL),
        ),
    ]
