# Generated by Django 4.1.3 on 2023-01-05 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_rename_client_account_client_cclient_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='cclient_account',
            new_name='client_account',
        ),
    ]
