# Generated by Django 4.1.3 on 2023-01-09 21:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('location', models.CharField(max_length=32,
                                              validators=[django.core.validators.MinLengthValidator(1)])),
                ('date', models.DateField()),
            ],
        ),
    ]
