# Generated by Django 4.1.3 on 2023-01-02 11:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('location', models.CharField(max_length=32,
                                              validators=[django.core.validators.MinLengthValidator(1)])),
                ('date', models.DateField()),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                to='supplier.supplier')),
            ],
        ),
    ]
