# Generated by Django 4.1.3 on 2023-01-09 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery_location', '0001_initial'),
        ('supplier', '0002_test_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverylocation',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='supplier.supplier'),
        ),
    ]
