# Generated by Django 4.1.3 on 2023-01-05 19:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier_product', '0002_test_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierproduct',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
