# Generated by Django 4.1.3 on 2023-01-02 11:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('user_name', models.CharField(help_text='User Name',
                                               max_length=32,
                                               primary_key=True,
                                               serialize=False,
                                               validators=[django.core.validators.MinLengthValidator(6)])),
                ('first_name', models.CharField(help_text='First Name',
                                                max_length=32,
                                                validators=[django.core.validators.MinLengthValidator(1)])),
                ('last_name', models.CharField(help_text='Last Name',
                                               max_length=32,
                                               validators=[django.core.validators.MinLengthValidator(1)])),
                ('password', models.CharField(help_text='Password',
                                              max_length=16,
                                              validators=[django.core.validators.MinLengthValidator(6)])),
                ('business_name', models.CharField(help_text='Business Name',
                                                   max_length=32,
                                                   validators=[django.core.validators.MinLengthValidator(6)])),
                ('supplier_account', models.OneToOneField(null=True,
                                                          on_delete=django.db.models.deletion.CASCADE,
                                                          to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
