# Generated by Django 4.1.3 on 2023-01-05 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0004_supplier_supplier_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='supplier_account',
            new_name='ssupplier_account',
        ),
    ]
