# Generated by Django 4.1.3 on 2023-01-05 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0005_rename_supplier_account_supplier_ssupplier_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='ssupplier_account',
            new_name='supplier_account',
        ),
    ]
