# Generated by Django 4.1.3 on 2023-01-09 21:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery_location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('quantity', models.IntegerField(default=1,
                                                 validators=[django.core.validators.MinValueValidator(1)])),
                ('delivery_location_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                           to='delivery_location.deliverylocation')),
            ],
        ),
    ]
