# Generated by Django 4.1.3 on 2023-01-09 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supplier_product', '0001_initial'),
        ('ordered_product', '0001_initial'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproduct',
            name='supplier_product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier_product.supplierproduct'),
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
    ]
